server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://db:3306/home_clothing_tester
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    com.homeclothing: DEBUG

springdoc:
  swagger-ui:
    path: /swagger